#!/bin/bash
#SBATCH --job-name=3.2_LRT_filter
#SBATCH --partition=uri-cpu
#SBATCH --time=01:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH --constraint=avx512
#SBATCH --mail-user="biancani@uri.edu"
#SBATCH --mail-type=ALL

# Source master parameters script:
vars="/scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# --- Environment Setup (Proven Unity Config) ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a

export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH
export R_LIBS=~/R-packages

# --- Execute ---
for random_seed in $seeds;
  do
  set_dir="set_$random_seed"
  echo "Running Likelihood Ratio Test for Simulation $set_dir";
  # input (generated by 3.1)
  IQ_DIR="$out3_1/$set_dir"
  OutDir="$out3_2/$set_dir"
  mkdir -p "$OutDir"
  OUT_FILE="$OutDir/lrt_results.csv"
  Rscript $LRTfilter "$IQ_DIR" "$OUT_FILE"
done
