#!/bin/bash
#SBATCH --job-name=filter_loci
#SBATCH --partition=uri-cpu
#SBATCH --time=00:10:00
#SBATCH --mem=1G

# --- Variables ---
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
Scripts="$Project/LociSimulation/Scripts/3_filter_by_known_clades"
Output="$Project/output/mammals"

# Inputs
# LRT csv generated by 3.2_LRT_filter.sh:
LRT_CSV="$Output/3.2_lrt_results/lrt_results.csv"
# Path to aligned loci generated by 2.4_restore_names.sh:
Alignments="$Output/2.4_final_named_alignments"
# p threshold:
Pvalue=0.05

# Output
FinalDir="$Output/3.3_loci_filtered_by_known_clades"
mkdir -p "$FinalDir"

# --- Environment ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a

export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH

# --- Execute ---
# Arguments: <CSV> <SourceDir> <DestDir> <P-Threshold>
Rscript $Scripts/collect_filtered_loci.R "$LRT_CSV" "$Alignments" "$FinalDir" "$Pvalue"

01~#!/bin/bash
#SBATCH --job-name=filter_loci
#SBATCH --partition=uri-cpu
#SBATCH --time=00:10:00
#SBATCH --mem=2G

# --- Variables ---
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
Scripts="$Project/LociSimulation/Scripts/3_filter_by_known_clades"
Output="$Project/output/mammals"

# Inputs
# LRT csv generated by 3.2_LRT_filter.sh:
LRT_CSV="$Output/3.2_lrt_results/lrt_results.csv"
# Path to aligned loci generated by 2.4_restore_names.sh:
Alignments="$Output/2.4_final_named_alignments"
# p threshold:
Pvalue=0.05

# Output
FinalDir="$Output/3.3_loci_filtered_by_known_clades"
mkdir -p "$FinalDir"

# --- Environment ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a

export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH

# --- Execute ---
# Arguments: <CSV> <SourceDir> <DestDir> <P-Threshold>
Rscript $Scripts/collect_filtered_loci.R "$LRT_CSV" "$Alignments" "$FinalDir" "$Pvalue"

