#!/bin/bash
#SBATCH --job-name=filter_loci
#SBATCH --partition=uri-cpu
#SBATCH --time=00:15:00
#SBATCH --mem=1G

# Source master parameters script:
vars="/scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# --- Environment ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH

# --- Execute ---
for random_seed in $seeds;
  do
  set_dir="set_$random_seed"
  echo "Collecting filtered loci for Simulation $set_dir";
  # input (LRT csv generated by 3.2)
  LRT_CSV="$out3_2/$set_dir/lrt_results.csv"
  # input (path to aligned loci generated by 2.4)
  Alignments="$out2_4/$set_dir"
  # output
  FinalDir="$out3_3/$set_dir"
  mkdir -p "$FinalDir"
  # Arguments: <CSV> <SourceDir> <DestDir> <P-Threshold>
  Rscript "$CFL" "$LRT_CSV" "$Alignments" "$FinalDir" "$Pvalue3_3"
done
