#!/bin/bash
#SBATCH --job-name=iqtree_emp
#SBATCH --partition=uri-cpu
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=30
#SBATCH --mem=16G
#SBATCH --constraint=avx512
#SBATCH --mail-user="biancani@uri.edu"
#SBATCH --mail-type=ALL

# Source master parameters script:
vars="/scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# Input empirical alignments (from 0_data_prep):
Alignments="$DATA"
# Input constraint trees (generated by 7.0)
Constraints="$out7_0"

OutDir="$out7_1"
mkdir -p "$OutDir"

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load parallel/20240822

# --- Command Factory Logic ---
run_iqtree() {
    locus_path="$1"
    filename=$(basename "$locus_path")
    locus_id="${filename%.*}"

    # 1. Unconstrained Run
    "$IQTREE" -s "$locus_path" -m GTR+G -pre "$OutDir/${locus_id}_uncon" -nt 1 -redo -quiet

    # 2. Constrained Run (only if constraint exists)
    const_file="$Constraints/${locus_id}_constraint.newick"
    if [ -f "$const_file" ]; then
        "$IQTREE" -s "$locus_path" -m GTR+G -g "$const_file" -pre "$OutDir/${locus_id}_con" -nt 1 -redo -quiet
    fi

    # Cleanup auxiliary files
    rm -f "$OutDir/${locus_id}_"*".ckp.gz" "$OutDir/${locus_id}_"*".bionj" "$OutDir/${locus_id}_"*".mldist"
}

export -f run_iqtree
export IQTREE OutDir Constraints

# --- Execute with GNU Parallel ---
find "$Alignments" -maxdepth 1 -regextype posix-extended -regex '.*\.(fas|fa|fasta)$' | \
    parallel --env IQTREE --env OutDir --env Constraints -j 30 --no-notice run_iqtree {}

echo "IQ-TREE inferences complete. Likelihoods saved in $OutDir"
