#!/bin/bash
#SBATCH --job-name="prep_simphy"
#SBATCH --time=6:00:00  # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=1   # processor core(s) per node
#SBATCH --mail-user="biancani@uri.edu" #CHANGE TO user email address
#SBATCH --mail-type=ALL
#SBATCH -p uri-cpu
#SBATCH -c 2
#SBATCH --mem-per-cpu=6G

# --- Variables ---
# Path to project directory:
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to scripts directory:
Scripts="$Project/LociSimulation/Scripts"
# Path to modified.write.tree2.R (script that adjusts how ape handles tree files)
mod_write_tree2=$Scripts/2_simulation_scripts/modified.write.tree2.R
# Path to output directory
Output="$Project/output/mammals"
# Path to reformatted ultrametric treefile and parameter file generated by 1.1_format_tree.sh
treefile=$Output/1.1_formatted_empirical_tree/s_tree.trees
params=$Output/1.1_formatted_empirical_tree/generate_params.txt

# create output subdirectory:
out_dir=$Output/2.0_simphy_prep
mkdir -p $out_dir
cd $out_dir

# --- Module Management ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a

# --- Critical Environment Fixes ---
# 1. Fix for the C++ library (GLIBCXX) errors
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH

# 2. Point R to your custom package library
export R_LIBS=~/R-packages

# --- generate_sim_properties.R ---

Rscript $Scripts/2_simulation_scripts/generate_sim_properties.R $treefile $params $mod_write_tree2

date
