#!/bin/bash
#SBATCH --job-name=simphy_cmd
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH -p uri-cpu
#SBATCH --time=1:00:00  # walltime limit (HH:MM:SS)
#SBATCH --mail-user="biancani@uri.edu" #CHANGE TO user email address
#SBATCH --mail-type=ALL

# --- Variables ---
# Path to project directory:
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to scripts directory:
Scripts="$Project/LociSimulation/Scripts"
# Path to output directory
Output="$Project/output/mammals"
# Path to SimPhy executable:
simphy_exe=/project/pi_rsschwartz_uri_edu/Biancani/Software/SimPhy/SimPhy_1.0.2/bin/simphy_lnx64

# Input files (Generated by 2.0_prep_simphy.sh)
tree_file=$Output/2.0_simphy_prep/sptree.nex
df_file=$Output/2.0_simphy_prep/df.csv

# create output subdirectory:
out_dir=$Output/2.1_commands_simphy
mkdir -p $out_dir
cd $out_dir

# Output files (To be generated)
cmd_list=$out_dir/simphy_command_list.txt
loci_out_dir=$Output/2.2_simulated_loci/ ## note: terminal "/" is necessary! ##

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a
# Fix for the C++ library (GLIBCXX) errors:
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH
# Point R to your custom package library
export R_LIBS=~/R-packages

# --- run_SimPhy.R ---

Rscript "$Scripts/2_simulation_scripts/run_SimPhy.R" \
    "$tree_file" \
    "$df_file" \
    "$cmd_list" \
    "$loci_out_dir" \
    "$simphy_exe"

date
