#!/bin/bash
#SBATCH --job-name=simphy_cmd
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=1G
#SBATCH -p uri-cpu
#SBATCH --time=0:20:00  # walltime limit (HH:MM:SS)
#SBATCH --mail-user="biancani@uri.edu" #CHANGE TO user email address
#SBATCH --mail-type=ALL

# Source master parameters script:
vars="/scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# create output subdirectory:
mkdir -p $out2_1
cd $out2_1

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a
# Fix for the C++ library (GLIBCXX) errors:
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH
# Point R to your custom package library
export R_LIBS=~/R-packages

# --- run_SimPhy.R ---

sets=$(echo $seeds | wc -w)
echo "Generating SimPhy commands for $sets set(s) of loci"
for random_seed in $seeds;
  do
  echo "Generating SimPhy commands for random seed: $random_seed";
  set_dir="set_$random_seed"
  mkdir -p "$set_dir"
  #input files (generated by 2.0_prep_simphy.sh):
  tree_file="$input2_1/$set_dir/sptree.nex"
  df_file="$input2_1/$set_dir/df.csv"
  #output files (to be generated)
  cmd_list="$out2_1/$set_dir/simphy_command_list.txt"
  loci_out_dir="$out2_2/$set_dir/" ## note: terminal "/" is necessary! ##
  mkdir -p $loci_out_dir
  Rscript "$RSP" \
      "$tree_file" \
      "$df_file" \
      "$cmd_list" \
      "$loci_out_dir" \
      "$simphy_exe"
  echo "SimPhy commands for $set_dir have been generated."
done

date
