#!/bin/bash
#SBATCH --job-name=simphy_run
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32        # Number of simulations to run in parallel
#SBATCH --mem=16G                 # Adjust based on node availability
#SBATCH -p uri-cpu
#SBATCH --constraint=avx512       # Required for foss/2024a on this cluster
#SBATCH --time=12:00:00
#SBATCH --mail-user="biancani@uri.edu"
#SBATCH --mail-type=ALL

# --- Variables ---
# Path to project directory:
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to project output directory
Output="$Project/output/mammals"

# Input file (generated by 2.1_simphy_commands.sh):
cmd_list="$Output/2.1_commands_simphy/simphy_command_list.txt"

# Output subdirectory for the simulations:
out_dir="$Output/2.2_simulated_loci"
mkdir -p "$out_dir"

# Output: final combined gene tree file
master_trees="$out_dir/gene_trees.tre"
# Initialize/clear the gene tree log file
> "$master_trees"

# Log: Tracks which simulations succeeded
job_log="$out_dir/2.2_parallel_joblog.log"

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load parallel/20240822

# --- 1. Initial Parallel Execution ---
echo "Starting initial SimPhy simulations..."

parallel --jobs $SLURM_CPUS_PER_TASK --joblog "$job_log" --progress < "$cmd_list"
# --jobs $SLURM_CPUS_PER_TASK: Uses the cores requested above
# --joblog: Records completion; if job fails, re-running will skip finished tasks
# --progress: Prints a progress bar and ETA to the slurm log

# --- 2. Validation & Auto-Recovery Loop ---
echo "Verifying simulation integrity..."

# We will loop until all files exist, or set a max number of retry attempts
MAX_RETRIES=2
RETRY_COUNT=0

while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
    FAILED_LOCI=()

    # Check each of the 2000 expected tree files
    for i in {1..2000}; do
        tree_file="$out_dir/loc_$i/1/g_trees1.trees"
        
        # If file doesn't exist (-f) OR is empty (! -s)
        if [[ ! -f "$tree_file" || ! -s "$tree_file" ]]; then
            FAILED_LOCI+=($i)
        fi
    done

    # If no failures, break the loop
    if [ ${#FAILED_LOCI[@]} -eq 0 ]; then
        echo "All 2,000 simulations verified successfully."
        break
    else
        RETRY_COUNT=$((RETRY_COUNT + 1))
        echo "WARNING: ${#FAILED_LOCI[@]} simulations failed. Starting Retry #$RETRY_COUNT..."
        
        # Log the failures
        echo "$(date): Attempt $RETRY_COUNT - Failed Loci: ${FAILED_LOCI[*]}" >> "$out_dir/retry_log.txt"

        # Re-run only the failed commands
        for locus_id in "${FAILED_LOCI[@]}"; do
            # Extract the specific line from the original command list
            # Since loci are loc_1 to loc_2000, we pull line $locus_id
            cmd=$(sed -n "${locus_id}p" "$cmd_list")
            
            echo "Re-running Locus $locus_id..."
            eval "$cmd"
        done
    fi
done

echo "Final check after retries..."
if [ ${#FAILED_LOCI[@]} -gt 0 ]; then
    echo "CRITICAL: ${#FAILED_LOCI[@]} loci still failing after $MAX_RETRIES retries. Check retry_log.txt"
    exit 1
fi

# --- 3. Sequential Harvesting ---
echo "All simulations verified. Starting sequential harvest into $master_trees..."

# Initialize/clear the master file
> "$master_trees"

# Loop from 1 to 2000 to ensure perfect numerical order
# Line 1 in the tree file will correspond to Locus 1 (Row 1 in df.csv)
for i in {1..2000}
do
    # Define the path to the replicate 1 tree file
    tree_file="$out_dir/loc_$i/1/g_trees1.trees"
    
    # Append the tree to the master file
    cat "$tree_file" >> "$master_trees"
done

echo "Harvesting complete at $(date)"

# --- 4. Final Verification ---
echo "Performing final audit of $master_trees..."

# Count the number of Newick trees (lines starting with '(')
actual_count=$(grep -c "(" "$master_trees")
expected_count=2000

if [ "$actual_count" -eq "$expected_count" ]; then
    echo "-------------------------------------------------------"
    echo " SUCCESS: 2.2_run_simulations.sh finished successfully."
    echo " Total Trees: $actual_count"
    echo " Order: Sequential (Locus 1 to 2000)"
    echo " Output file: $master_trees"
    echo "-------------------------------------------------------"
else
    echo "-------------------------------------------------------"
    echo " ERROR: Final tree count ($actual_count) does not match"
    echo " expected count ($expected_count)."
    echo " Please check $out_dir/retry_log.txt for clues."
    echo "-------------------------------------------------------"
    exit 1
fi

date
