#!/bin/bash
#SBATCH --job-name=restore_names
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH -p uri-cpu
#SBATCH --time=00:20:00
#SBATCH --mail-user="biancani@uri.edu"
#SBATCH --mail-type=ALL

# --- Variables ---
Project="/scratch4/workspace/biancani_uri_edu-LociSimulation"
Scripts="$Project/LociSimulation/Scripts"
Output="$Project/output/mammals"

# Input: final alignments with numbered taxa (generated by 2.3_INDELible.sh)
Input_Aln="$Output/2.3_indelible/alignments_final"
# Output path for final alignments with restored names (will be created if needed)
Final_Aln="$Output/2.4_final_named_alignments"
# Taxon map (generated by 1.1_format_tree.sh)
Taxon_Map="$Output/1.1_formatted_empirical_tree/taxon_map.csv"

mkdir -p "$Final_Aln"

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a

export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH
export R_LIBS=~/R-packages

# --- Execute Renaming ---
echo "Restoring empirical taxon names using taxon_map.csv..."
Rscript "$Scripts/2_simulation_scripts/restore_names.R" \
    "$Input_Aln" \
    "$Final_Aln" \
    "$Taxon_Map"

echo "Process complete. Final alignments located in: $Final_Aln"
date
