#!/bin/bash
#SBATCH --job-name=restore_names
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=4G
#SBATCH -p uri-cpu
#SBATCH --time=00:20:00
#SBATCH --mail-user="biancani@uri.edu"
#SBATCH --mail-type=ALL

# Source master parameters script:
vars="/scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh"
source $vars
echo "Variables sourced into current shell environment:"
cat $vars

# --- Environment Setup ---
module purge
module load uri/main
module load foss/2024a
module load R/4.3.2-gfbf-2023a
export GLIBCXX_PATH="/modules/uri_apps/software/GCCcore/13.3.0/lib64"
export LD_LIBRARY_PATH=$GLIBCXX_PATH:$LD_LIBRARY_PATH
export R_LIBS=~/R-packages

# --- Execute Renaming ---
for random_seed in $seeds;
  do
  set_dir="set_$random_seed"
  echo "Restoring empirical taxon names for $set_dir...";
  # Input: final alignments with numbered taxa (generated by 2.3)
  Input_Aln="$input2_4/$set_dir/alignments_final"
  # Output path for final alignment with restored names (will be created if needed)
  Final_Aln="$out2_4/$set_dir"
  mkdir -p "$Final_Aln"
  Rscript "$ReName" \
      "$Input_Aln" \
      "$Final_Aln" \
      "$Taxon_Map"
  echo "Name restoration complete. Final alignments located in: $Final_Aln"
done
