################################################
# variables.sh
# full path: /scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh
# variables are grouped by their first point of use but remain available for all subsequent scripts.

set -a  # Automatically export all variables defined after this line

## 0_data_prep

# Path to workspace:
WORK="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to empircial data (aligned loci in fasta format):
DATA="$WORK/mammal_loci/01_SISRS_loci_filtered"
# Path to parent output directory:
OUTPUT="$WORK/output"
# Path to dataset-specific output directory (named for empirical dataset):
Output="$OUTPUT/mammals"

# Path to simulation project directory:
PROJECT="$WORK/LociSimulation"
# Path to scripts directory:
SCRIPTS="$PROJECT/Scripts"

## 0.0_amas_concat.sh

# Path to script-specific output directory:
out0_0="$Output/0.0_concatenated"
# Path to AMAS executable:
AMAS="/project/pi_rsschwartz_uri_edu/Biancani/Software/AMAS/amas/AMAS.py"
# Path to run_amas.py:
run_amas="$SCRIPTS/0_data_prep/run_amas.py"

## 0.1_iqtree_empirical.sh

# Path to script-specific output directory:
out0_1="$Output/0.1_empirical_tree"
# Path to IQTREE executable:
IQTREE="/project/pi_rsschwartz_uri_edu/Biancani/Software/iqtree-2.1.2-Linux/bin/iqtree2"

## 1_prep_empirical_tree

# List of necessary R packages (separated by spaces)
R_packages="igraph phangorn MASS clusterGeneration ape ggplot2 phytools geiger MultiRNG EnvStats extraDistr tidyverse castor Quartet"
# Local directory to install R packages (will be created if necessary)
R_package_DIR="/home/biancani_uri_edu/R-packages"

## 1.1_format_tree.sh

# Path to modified.write.tree2.R (script that adjusts how ape handles tree files):
mod_write_tree2=$SCRIPTS/2_simulation_scripts/modified.write.tree2.R
# Path to treefile generated by 0.1_iqtree_empirical.sh:
input1_1=$out0_1/inferenceEmpirical.treefile
# List of outgroup taxa for tree rooting (comma separated)
outgroup="Wallabia_bicolor,Potorous_gilbertii,Pseudochirops_corinnae,Gymnobelideus_leadbeateri,Phalanger_gymnotis,Vombatus_ursinus,Phascolarctos_cinereus,Thylacinus_cynocephalus,Sarcophilus_harrisii,Didelphis_virginiana"
# Total tree depth: Estimated age (in years) of most recent common ancestor of all species in the tree:
tree_depth=168000000
# Generation time: Estimated generation time (in years) of all species in the tree:
gen_time=4.5
# Path to script-specific output directory:
out1_1="$Output/1.1_formatted_empirical_tree"

## 2_simulation_scripts

## 2.0_prep_simphy.sh

# path to reformatted ultarmetric treefile generated by 1.1_format_tree.sh
input2_0="$out1_1/s_tree.trees"
# Path to script-specific output directory:
out2_0="$Output/2.0_simphy_prep"
# Path to generate_sim_properties.R:
GSP="$SCRIPTS/2_simulation_scripts/generate_sim_properties.R"

## Simulation Parameters:
# Number of loci to simulate per simulation set
nloci=2000
# List of random number seeds (1 per simulation set, separated by a space) for reproducibility:
seeds="12345 67890 23456 78901 34567"
# Natural Log range for Average Branch Length (ABL) for group
ABLmin=-20
ABLmax=-15
# Variance in Branch Length (VBL) - models heterotachy (rate variance) across the tree
VBLmin=0.5
VBLmax=5.0
# Proportion of loci to be protein coding - CODON model (vs. NUCLEOTIDE model)
PropCoding=0.5
# Range for simulated locus length (bp) - shorter loci yield more noise
LLmin=200
LLmax=2000
# LambdaPS Pagel's Lambda - Scales proportion of phylogenetic signal on internal branches
lambdaPSmin=0.5
lambdaPSmax=1.0
# Effective Population Size - ILS level Scales discordance based on Ne of the empirical group
Ne=100000
## Missing Data Simulation
# Maximum Proportion of entirely missing taxa permitted (per locus)
MissTaxa=0.5
# Proportion of non-missing sequences to exhibit partial data loss:
PartLoss=0.5
# Proportion of locus sequence removed (for taxa exhibiting partial loss):
MissPropMIN=0.2
MissPropMAX=0.6
## Paralogy and Contamination Simulation
# Proportion of loci exhibiting no paralogy (clean)
NoParalogy=0.5
# The average proportion of taxa exhibiting paralogous signal in a given non-orthologous locus
ParalogyIntensity=0.1
# Proportion of loci exhibiting no contamination (clean)
NoContaminant=0.5
# The average proportion of taxa exhibiting contamination (swaps) in a given contaminated locus
ContaminantIntensity=0.1

## 2.1_simphy_commands.sh

# Path to SimPhy executable:
simphy_exe="/project/pi_rsschwartz_uri_edu/Biancani/Software/SimPhy/SimPhy_1.0.2/bin/simphy_lnx64"
# Path to run_SimPhy.R:
RSP="$SCRIPTS/2_simulation_scripts/run_SimPhy.R"
# Path to script-specific output directory:
out2_1="$Output/2.1_commands_simphy"
# Path to directory containing input files (output of 2.0_prep_simphy.sh)
input2_1="$out2_0"

## 2.2_submit_sim_jobs.sh

# Path to script-specific output directory:
out2_2="$Output/2.2_simulated_loci"
# Path to run_simulations.sh
RSim="$SCRIPTS/2_simulation_scripts/run_simulations.sh"

## 2.3_submit_INDELible.sh

# Path to run_INDELible.sh
RIND="$SCRIPTS/2_simulation_scripts/run_INDELible.sh"
# Path to INDELible executable
indel_exe="/project/pi_rsschwartz_uri_edu/Biancani/Software/indelible/src/indelible"
# Path to script-specific output directory:
out2_3="$Output/2.3_indelible"
# Path to prep_INDELible.R
prepIND="$SCRIPTS/2_simulation_scripts/prep_INDELible.R"
# Path to post_INDELible.R
postIND="$SCRIPTS/2_simulation_scripts/post_INDELible.R"
# Path to modify_gene_tree.R
modify_gene_tree="$SCRIPTS/2_simulation_scripts/modify_gene_tree.R"

## 2.4_restore_names.sh

# Taxon map (generated by 1.1_format_tree.sh)
Taxon_Map="$Output/1.1_formatted_empirical_tree/taxon_map.csv"
# Input directory (output of 2.3_submit_INDELible.sh)
input2_4="$out2_3"
# Path to script-specific output directory:
out2_4="$Output/2.4_final_named_alignments"
# Path to restore_names.R
ReName="$SCRIPTS/2_simulation_scripts/restore_names.R"

## 3. Filter by Known clades

## 3.0_submit_generate_constraints.sh

# Path to generate_constraints.sh
GenCon="$SCRIPTS/3_filter_by_known_clades/generate_constraints.sh"
# Path to generate_constraints.R
GenConR="$SCRIPTS/3_filter_by_known_clades/generate_constraints.R"
# Path to script-specific output directory:
out3_0="$Output/3.0_constraint_trees"
# Input clades: a taxon-to-group correspondence CSV table with the following format:
# Group,Taxa
# group1,taxonName1
# group1,taxonName2
# group2,taxonName3
# group2,taxonName4
clades=/scratch4/workspace/biancani_uri_edu-LociSimulation/mammal_loci/groups.csv

## 3.1_submit_iqtree_likelihoods.sh

# Path to iqtree_likelihoods.sh
IQTL="$SCRIPTS/3_filter_by_known_clades/iqtree_likelihoods.sh"
# Path to script-specific output directory:
out3_1="$Output/3.1_likelihoods"

## 3.2_LRT_filter.sh

# Path to script-specific output directory:
out3_2="$Output/3.2_lrt_results"
# Path to LRT_filter.R:
LRTfilter="$SCRIPTS/3_filter_by_known_clades/LRT_filter.R"

## 3.3_collect_filtered_loci.sh

# Path to collect_filtered_loci.R
CFL="$SCRIPTS/3_filter_by_known_clades/collect_filtered_loci.R"
# p threshold:
Pvalue3_3=0.05
# Path to script-specific output directory:
out3_3="$Output/3.3_loci_filtered_by_known_clades"

## 4. Filter by Branch Length Correlation

## 4.0_submit_concat_tree.sh

# Path to concat_tree.sh
concat_tree="$SCRIPTS/4_filter_by_branch_length/concat_tree.sh"
# Path to script-specific output directory:
out4_0="$Output/4.0_unfiltered_concat_tree"

## 4.1_submit_constrained_gtrees.sh

# Path to constrained_gtrees.sh
CGT="$SCRIPTS/4_filter_by_branch_length/constrained_gtrees.sh"
# Path to trimConstraintTree.R
TCT="$SCRIPTS/4_filter_by_branch_length/trimConstraintTree.R"
# Path to script-specific output directory:
out4_1="$Output/4.1_constrained_gtrees"

## 4.2_submit_treescreen.sh

# Path to treescreen.sh
TScreen="$SCRIPTS/4_filter_by_branch_length/treescreen.sh"
# Path to treescreen.R
TScreenR="$SCRIPTS/4_filter_by_branch_length/treescreen.R"
# Path to script-specific output directory:
out4_2="$Output/4.2_BLC_filtered"

## 6. Infer and Compare Trees

## 6.1_submit_create_intersections.sh

# Path to create_intersections.sh
Intersects="$SCRIPTS/6_infer_and_compare_trees/create_intersections.sh"
# Path to script-specific output directory:
out6_1="$Output/6.1_intersection_data"

set +a  # Stop automatically exporting
################################################
