################################################
# variables.sh
# full path: /scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh
# variables are grouped by their first point of use but remain available for all subsequent scripts.

set -a  # Automatically export all variables defined after this line

## 0_data_prep

# Path to workspace:
WORK="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to empircial data (aligned loci in fasta format):
DATA="$WORK/mammal_loci/01_SISRS_loci_filtered"
# Path to parent output directory:
OUTPUT="$WORK/output"
# Path to dataset-specific output directory (named for empirical dataset):
Output="$OUTPUT/mammals"

# Path to simulation project directory:
PROJECT="$WORK/LociSimulation"
# Path to scripts directory:
SCRIPTS="$PROJECT/Scripts"

## 0.0_amas_concat.sh

# Path to script-specific output directory:
out0_0="$Output/0.0_concatenated"
# Path to AMAS executable:
AMAS="/project/pi_rsschwartz_uri_edu/Biancani/Software/AMAS/amas/AMAS.py"

## 0.1_iqtree_empirical.sh

# Path to script-specific output directory:
out0_1="$Output/0.1_empirical_tree"
# Path to IQTREE executable:
IQTREE="/project/pi_rsschwartz_uri_edu/Biancani/Software/iqtree-2.1.2-Linux/bin/iqtree2"

## 1_prep_empirical_tree

# List of necessary R packages (separated by spaces)
R_packages="igraph phangorn MASS clusterGeneration ape ggplot2 phytools geiger MultiRNG EnvStats extraDistr tidyverse castor Quartet"
# Local directory to install R packages (will be created if necessary)
R_package_DIR="/home/biancani_uri_edu/R-packages"

## 1.1_format_tree.sh

# Path to modified.write.tree2.R (script that adjusts how ape handles tree files):
mod_write_tree2=$SCRIPTS/2_simulation_scripts/modified.write.tree2.R
# Path to treefile generated by 0.1_iqtree_empirical.sh:
input1_1=$out0_1/inferenceEmpirical.treefile
# List of outgroup taxa for tree rooting (comma separated)
outgroup="Wallabia_bicolor,Potorous_gilbertii,Pseudochirops_corinnae,Gymnobelideus_leadbeateri,Phalanger_gymnotis,Vombatus_ursinus,Phascolarctos_cinereus,Thylacinus_cynocephalus,Sarcophilus_harrisii,Didelphis_virginiana"
# Total tree depth: Estimated age (in years) of most recent common ancestor of all species in the tree:
tree_depth=168000000
# Generation time: Estimated generation time (in years) of all species in the tree:
gen_time=4.5
# Path to script-specific output directory:
out1_1="$Output/1.1_formatted_empirical_tree"



set +a  # Stop automatically exporting
################################################
