################################################
# variables.sh
# full path: /scratch4/workspace/biancani_uri_edu-LociSimulation/LociSimulation/Scripts/variables.sh
# variables are grouped by their first point of use but remain available for all subsequent scripts.

set -a  # Automatically export all variables defined after this line

## 0_data_prep

# Path to workspace:
WORK="/scratch4/workspace/biancani_uri_edu-LociSimulation"
# Path to empircial data (aligned loci in fasta format):
DATA="$WORK/mammal_loci/01_SISRS_loci_filtered"
# Path to parent output directory:
OUTPUT="$WORK/output"
# Path to dataset-specific output directory (named for empirical dataset):
Output="$OUTPUT/mammals"

# Path to simulation project directory:
PROJECT="$WORK/LociSimulation"
# Path to scripts directory:
SCRIPTS="$PROJECT/Scripts"

## 0.0_amas_concat.sh

# Path to script-specific output directory:
out0_0="$Output/0.0_concatenated"
# Path to AMAS executable:
AMAS="/project/pi_rsschwartz_uri_edu/Biancani/Software/AMAS/amas/AMAS.py"

## 0.1_iqtree_empirical.sh

# Path to script-specific output directory:
out0_1="$Output/0.1_empirical_tree"
# Path to IQTREE executable:
IQTREE="/project/pi_rsschwartz_uri_edu/Biancani/Software/iqtree-2.1.2-Linux/bin/iqtree2"

## 1_prep_empirical_tree

# List of necessary R packages (separated by spaces)
R_packages="igraph phangorn MASS clusterGeneration ape ggplot2 phytools geiger MultiRNG EnvStats extraDistr tidyverse castor Quartet"
# Local directory to install R packages (will be created if necessary)
R_package_DIR="/home/biancani_uri_edu/R-packages"

## 1.1_format_tree.sh

# Path to modified.write.tree2.R (script that adjusts how ape handles tree files):
mod_write_tree2=$SCRIPTS/2_simulation_scripts/modified.write.tree2.R
# Path to treefile generated by 0.1_iqtree_empirical.sh:
input1_1=$out0_1/inferenceEmpirical.treefile
# List of outgroup taxa for tree rooting (comma separated)
outgroup="Wallabia_bicolor,Potorous_gilbertii,Pseudochirops_corinnae,Gymnobelideus_leadbeateri,Phalanger_gymnotis,Vombatus_ursinus,Phascolarctos_cinereus,Thylacinus_cynocephalus,Sarcophilus_harrisii,Didelphis_virginiana"
# Total tree depth: Estimated age (in years) of most recent common ancestor of all species in the tree:
tree_depth=168000000
# Generation time: Estimated generation time (in years) of all species in the tree:
gen_time=4.5
# Path to script-specific output directory:
out1_1="$Output/1.1_formatted_empirical_tree"

## 2_simulation_scripts

## 2.0_prep_simphy.sh

# path to reformatted ultarmetric treefile generated by 1.1_format_tree.sh
input2_0="$out1_1/s_tree.trees"
# Path to script-specific output directory:
out2_0="$Output/2.0_simphy_prep"
# Path to generate_sim_properties.R:
GSP="$SCRIPTS/2_simulation_scripts/generate_sim_properties.R"

## Simulation Parameters:
# Number of loci to simulate per simulation set
nloci=2000
# List of random number seeds (1 per simulation set, separated by a space) for reproducibility:
seeds="12345 67890 23456 78901 34567"
# Natural Log range for Average Branch Length (ABL) for group
ABLmin=-20
ABLmax=-15
# Variance in Branch Length (VBL) - models heterotachy (rate variance) across the tree
VBLmin=0.5
VBLmax=5.0
# Proportion of loci to be protein coding - CODON model (vs. NUCLEOTIDE model)
PropCoding=0.5
# Range for simulated locus length (bp) - shorter loci yield more noise
LLmin=200
LLmax=2000
# LambdaPS Pagel's Lambda - Scales proportion of phylogenetic signal on internal branches
lambdaPSmin=0.5
lambdaPSmax=1.0
# Effective Population Size - ILS level Scales discordance based on Ne of the empirical group
Ne=100000
## Missing Data Simulation
# Maximum Proportion of entirely missing taxa permitted (per locus)
MissTaxa=0.5
# Proportion of non-missing sequences to exhibit partial data loss:
PartLoss=0.5
# Proportion of locus sequence removed (for taxa exhibiting partial loss):
MissPropMIN=0.2
MissPropMAX=0.6

## Paralogy and Contamination Simulation
# Proportion of loci exhibiting no paralogy (clean)
NoParalogy=0.5
# The average proportion of taxa exhibiting paralogous signal in a given non-orthologous locus
ParalogyIntensity=0.1
# Proportion of loci exhibiting no contamination (clean)
NoContaminant=0.5
# The average proportion of taxa exhibiting contamination (swaps) in a given contaminated locus
ContaminantIntensity=0.1

set +a  # Stop automatically exporting
################################################
