## Capture Command Line Arguments

# Arguments must be passed in the following order:
# [1] mod_write_tree2     (Path to modified.write.tree2.R - script that adjusts how ape handles tree files)
# [2] treefile            (Path to the input .treefile - generated by 0.1_iqtree_empirical.sh)
# [3] format_tree_out     (Base directory for output files)
# [4] outgroup            (List of comma separated outgroup taxa for tree rooting)
# [5] tree_depth          (Estimated age in years of most recent common ancestor of all species in the tree)
# [6] gen_time            (Estimated generation time in years for all species in the tree)
# [7] simphy_seed1        (First random number seed for generate_params.txt)
# [8] simphy_seed2        (Second random number seed for generate_params.txt)

args <- commandArgs(trailingOnly = TRUE)

# Check if the correct number of arguments was provided
if (length(args) < 8) {
  stop("Error: Not enough arguments provided. Expected 8.", call. = FALSE)
}

# Assign arguments to variables
mod_write_tree2 <- args[1]
treefile <- args[2]
format_tree_out <- args[3]
outgroup <- args[4]
simphy_seed1 <- args[7]
simphy_seed2 <- args[8]

# Calculate the scale factor (Total Generations) from args[5] (depth) and args[6] (gen_time)
scale_factor <- as.numeric(args[5])/as.numeric(args[6])

# --- 2. Load Libraries and Setup ---

library(ape)
library(ggplot2)
library(geiger)
library(ggtree)

## Force a headless friendly bitmap device for the session
options(bitmapType = "cairo")

# Adjust path to modified.write.tree2.R
source(mod_write_tree2)
assignInNamespace(".write.tree2", .write.tree2, "ape")

# --- 3. Process and Save Empirical Tree ---

# Empirical tree:
tree <- read.tree(treefile)

# 1. Convert the comma-separated string into a vector of tip labels
outgroup_taxa <- unlist(strsplit(outgroup, ","))

# 2. Check that the taxa are actually in the tree
if (!all(outgroup_taxa %in% tree$tip.label)) {
    # Check if any taxa in the list are missing from the tree
    missing_taxa <- setdiff(outgroup_taxa, tree$tip.label)
    stop(paste("Error: The following outgroup taxa were not found in the tree:", paste(missing_taxa, collapse=", ")), call.=FALSE)
}

# 3. Find the Most Recent Common Ancestor (MRCA) node index
# getMRCA returns the node index that is ancestral to all tips in the vector
outgroup_node <- getMRCA(phy = tree, tip = outgroup_taxa)

# 4. Root the tree using the identified MRCA node index
# Use the node= argument instead of outgroup=
tree <- root(tree, node = outgroup_node, resolve.root = TRUE)

# Save the check image
p <- ggtree(tree) + theme_tree2() + geom_tiplab()
ggsave(p, file=paste0(format_tree_out, "/tree_check_root.png"))

# Check the tree rooted correctly. Then transform to ultrametric and rescale

tree_um <- chronos(tree)
class(tree_um) <- "phylo" # Ensure it is a 'phylo' object after chronos
tree_um <- rescale(tree_um, model = "depth", scale_factor)

# Save the ultrametric tree check image
q <- ggtree(tree_um) + theme_tree2() + geom_tiplab()
ggsave(q, file=paste0(format_tree_out, "/tree_um.png"))

# --- 4. Prepare for SimPhy and Write Outputs ---

taxon_map <- data.frame(number = 1:length(tree_um$tip.label), name = tree_um$tip.label)
write.csv(taxon_map, paste0(format_tree_out, "/taxon_map.csv"), row.names = FALSE)

# Replace labels with numbers, strip node labels, and write out the tree
tree_um$tip.label <- as.character(1:length(tree_um$tip.label))
tree_um$node.label <- NULL
write.tree(tree_um, paste0(format_tree_out, "/s_tree.trees"), digits=8)

# Write the seeds for subsequent dataset parameter simulations
write(c(simphy_seed1, simphy_seed2), paste0(format_tree_out, "/generate_params.txt"))

print("Tree processing complete and output files saved.")
